apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=6d07370aec1a37810b9776a77250c49ae0c2654b

namespace: release-service
